version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    container_name: redai_frontend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - redai-network

  backend:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: redai_backend_prod
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DEBUG=false
              - AZURE_OPENAI_API_KEY=YOUR_AZURE_OPENAI_API_KEY_HERE
              - AZURE_OPENAI_BACKUP_KEY=YOUR_AZURE_OPENAI_BACKUP_KEY_HERE
      - AZURE_OPENAI_ENDPOINT=https://neuroflow-hub.openai.azure.com
      - AZURE_OPENAI_API_VERSION=2024-05-01-preview
      - AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4.1
      - USE_AZURE_AD=false
    restart: unless-stopped
    networks:
      - redai-network

networks:
  redai-network:
    driver: bridge

volumes:
  redis_data: 